import Link from "next/link";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { cn } from "@/lib/utils";

const categories = [
  {
    title: "Support",
    questions: [
      {
        question: "How do I connect my Amazon store to QuickBoarder?",
        answer:
          "Head to the ‘Integrations’ section in your QuickBoarder dashboard, choose your preferred platform, and follow the on-screen connection steps. You’ll be asked to authorize access to your store so we can publish and sync product listings automatically.",
      },
      {
        question: "Can I edit the generated product details?",
        answer:
          "Yes, absolutely. Every listing generated by QuickBoarder can be customized before export. You can fine-tune titles, descriptions, and images to better fit your brand tone and marketplace requirements.",
      },
    ],
  },
  {
    title: "Your account",
    questions: [
      {
        question: "How do I create or set up my QuickBoarder account?",
        answer:
          "You can sign up using your email address or Google account on our homepage. Once registered, you’ll gain access to your dashboard where you can start generating listings and connecting marketplaces instantly.",
      },
      {
        question: "Is QuickBoarder free to use or does it have paid plans?",
        answer:
          "QuickBoarder offers a free plan with limited AI credits to help you get started. For advanced features, higher credit limits, and priority export options, you can upgrade to a paid plan anytime from your account settings.",
      },
      {
        question: "Can I delete my data or account permanently?",
        answer:
          "Yes. You can request permanent deletion of your account and all related data from your profile settings. Once confirmed, all your stored product data, connections, and history will be erased from our servers.",
      },
    ],
  },
  {
    title: "Other questions",
    questions: [
      {
        question: "What is QuickBoarder and how does it work?",
        answer:
          "QuickBoarder is an AI-powered platform that helps you take your business online in minutes. Simply upload your product details or images, and our AI generates e-commerce–ready listings — complete with titles, descriptions, and visuals — that you can export to major marketplaces like Amazon, Flipkart, and Shopify.",
      },
      {
        question: "Can QuickBoarder create a complete product catalog?",
        answer:
          "Yes! With just basic product details or reference images, QuickBoarder can generate a full e-commerce catalog, including optimized titles, high-quality images, and keyword-rich descriptions — all ready for publishing.",
      },
      {
        question: "Which platforms does QuickBoarder support for export?",
        answer:
          "QuickBoarder currently supports exports to Amazon, Flipkart, Shopify, and WooCommerce. We’re continuously adding support for more marketplaces and will notify you when new integrations go live.",
      },
    ],
  },
];

export const FAQ = ({
  headerTag = "h2",
  className,
  className2,
}: {
  headerTag?: "h1" | "h2";
  className?: string;
  className2?: string;
}) => {
  return (
    <section className={cn("py-28 lg:py-32", className)}>
      <div className="container max-w-5xl">
        <div className={cn("mx-auto grid gap-16 lg:grid-cols-2", className2)}>
          <div className="space-y-4">
            {headerTag === "h1" ? (
              <h1 className="text-2xl tracking-tight md:text-4xl lg:text-5xl">
                Got Questions?
              </h1>
            ) : (
              <h2 className="text-2xl tracking-tight md:text-4xl lg:text-5xl">
                Got Questions?
              </h2>
            )}
            <p className="text-muted-foreground max-w-md leading-snug lg:mx-auto">
              If you can't find what you're looking for,{" "}
              <Link href="/contact" className="underline underline-offset-4">
                get in touch
              </Link>
              .
            </p>
          </div>

          <div className="grid gap-6 text-start">
            {categories.map((category, categoryIndex) => (
              <div key={category.title} className="">
                <h3 className="text-muted-foreground border-b py-4">
                  {category.title}
                </h3>
                <Accordion type="single" collapsible className="w-full">
                  {category.questions.map((item, i) => (
                    <AccordionItem key={i} value={`${categoryIndex}-${i}`}>
                      <AccordionTrigger>{item.question}</AccordionTrigger>
                      <AccordionContent className="text-muted-foreground">
                        {item.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
